version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: service-shoppan-dev
    environment:
      - PORT=3300
      - DATABASE_URL=postgres://postgres:12345678@db:5432/postgres
    ports:
      - '3300:3300'
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - '3600:5432'
    environment:
      - POSTGRES_PASSWORD=12345678
    container_name: shoppan-dev-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data