version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: service-shoppan-dev
    environment:
      - PORT=3300
      - DATABASE_URL=postgres://postgres:12345678@db:5432/postgres
      - JWT_SECRET=804621c271b74ae3e2772b3c120b9eb362c17dba1b7bee7930329e2af02dec26a418d28016c7737fa8036459078d3d5deec1bd07c392ba2a816fbab4514496d7
    ports:
      - '3300:3300'
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - '3600:5432'
    environment:
      - POSTGRES_PASSWORD=12345678
    container_name: shoppan-dev-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data